accent = "#6a6a95"
cursor = "#d9607d"
foreground = "#d9607d"
background = "#162533"
selection_foreground = "#d9607d"
selection_background = "#6a6a95"

color0 = "#162533"
color1 = "#9c413e"
color2 = "#29a0d6"
color3 = "#d92640"
color4 = "#6a6a95"
color5 = "#96698e"
color6 = "#349bcb"
color7 = "#ee5b6e"
color8 = "#3b4957"
color9 = "#c6615e"
color10 = "#60bfe8"
color11 = "#f29eaa"
color12 = "#9393b5"
color13 = "#c4a8c0"
color14 = "#a5d4ec"
color15 = "#d9607d"
